dg_defaults:
  url: "http://192.168.100.13:3333/api/inspector/marks"
  action: "list"
  headers:
    User-Arena: "first"
    Content-Type: "application/json"
    Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVyYWRtaW4iLCJncm91cFRhZyI6InJvb3QiLCJpYXQiOjE3NzAyMzE0MDN9.8c1qn3Ig8DeILOoe-09Vq1vjHNSMsbikrUmfghaHlHw"

dg_sources:
  - name: "ozon"
    schedule: 300
    payload_data:
      id: "5,6"
      type: "shost"
      expire: -1

  - name: "ozon-api"
    schedule: 300
    payload_data:
      id: "3,4"
      type: "shost"
      expire: -1
