ab_client:
  url: "http://192.168.100.13/common_ipban"
  interval: 20.0

nats:
  url: "nats://localhost:4222"
  dg_consumer:
    subject: "dg.load.command"
    durable: "dg_consumer"

parser:
  clickhouse_dt_format: "%Y-%m-%d %H:%M:%S"
